#ifndef ABYSS_RESOURCEPATHS_H
#define ABYSS_RESOURCEPATHS_H

#define CURSOR_DEFAULT "/data/global/ui/CURSOR/ohand.DC6"

// -- Main Menu
#define TRADEMARK_SCREEN   "/data/global/ui/FrontEnd/trademarkscreenEXP.dc6"
#define GAME_SELECT_SCREEN "/data/global/ui/FrontEnd/gameselectscreenEXP.dc6"
#define D2LOGO_BLACK_LEFT  "/data/global/ui/FrontEnd/D2logoBlackLeft.DC6"
#define D2LOGO_BLACK_RIGHT "/data/global/ui/FrontEnd/D2logoBlackRight.DC6"
#define D2LOGO_FIRE_LEFT   "/data/global/ui/FrontEnd/D2logoFireLeft.DC6"
#define D2LOGO_FIRE_RIGHT  "/data/global/ui/FrontEnd/D2logoFireRight.DC6"

// --

#define LOADING_SCREEN "/data/global/ui/loading/loadingscreen.dc6"

// -- Palettes
#define PALETTE_PATH       "/data/global/palette/%s/pal.dat"
#define PALETTE_ACT_1      "act1"
#define PALETTE_ACT_2      "act2"
#define PALETTE_ACT_3      "act3"
#define PALETTE_ACT_4      "act4"
#define PALETTE_ACT_5      "act5"
#define PALETTE_END_GAME   "endgame"
#define PALETTE_END_GAME_2 "endgame2"
#define PALETTE_FECHAR     "fechar"
#define PALETTE_LOADING    "loading"
#define PALETTE_MENU_0     "menu0"
#define PALETTE_MENU_1     "menu1"
#define PALETTE_MENU_2     "menu2"
#define PALETTE_MENU_3     "menu3"
#define PALETTE_MENU_4     "menu4"
#define PALETTE_SKY        "sky"
#define PALETTE_STATIC     "static"
#define PALETTE_TRADEMARK  "trademark"
#define PALETTE_UNITS      "units"

// -- Fonts
#define FONTS_FONT6          "/data/local/FONT/%s/font6"
#define FONTS_FONT8          "/data/local/FONT/%s/font8"
#define FONTS_FONT16         "/data/local/FONT/%s/font16"
#define FONTS_FONT24         "/data/local/FONT/%s/font24"
#define FONTS_FONT30         "/data/local/FONT/%s/font30"
#define FONTS_FONT42         "/data/local/FONT/%s/font42"
#define FONTS_FONTFORMAL10   "/data/local/FONT/%s/fontformal10"
#define FONTS_FONTFORMAL11   "/data/local/FONT/%s/fontformal11"
#define FONTS_FONTFORMAL12   "/data/local/FONT/%s/fontformal12"
#define FONTS_FONTEXOCET8    "/data/local/FONT/%s/fontexocet8"
#define FONTS_FONTEXOCET10   "/data/local/FONT/%s/fontexocet10"
#define FONTS_FONTSUCKER     "/data/local/FONT/%s/ReallyTheLastSucker"
#define FONTS_FONTREDICULOUS "/data/local/FONT/%s/fontridiculous"

// -- Music
#define MUSIC_TITLE                     "/data/global/music/introedit.wav"
#define MUSIC_OPTIONS                   "/data/global/music/Common/options.wav"
#define MUSIC_ACT1_ANDARIELACTION       "/data/global/music/Act1/andarielaction.wav"
#define MUSIC_ACT1_BLOODRAVENRESOLUTION "/data/global/music/Act1/bloodravenresolution.wav"
#define MUSIC_ACT1_CAVES                "/data/global/music/Act1/caves.wav"
#define MUSIC_ACT1_CRYPT                "/data/global/music/Act1/crypt.wav"
#define MUSIC_ACT1_DENOFEVILACTION      "/data/global/music/Act1/denofevilaction.wav"
#define MUSIC_ACT1_MONASTERY            "/data/global/music/Act1/monastery.wav"
#define MUSIC_ACT1_TOWN1                "/data/global/music/Act1/town1.wav"
#define MUSIC_ACT1_TRISTRAM             "/data/global/music/Act1/tristram.wav"
#define MUSIC_ACT1_WILD                 "/data/global/music/Act1/wild.wav"
#define MUSIC_ACT2_DESERT               "/data/global/music/Act2/desert.wav"
#define MUSIC_ACT2_HAREM                "/data/global/music/Act2/harem.wav"
#define MUSIC_ACT2_HORADRICACTION       "/data/global/music/Act2/horadricaction.wav"
#define MUSIC_ACT2_LAIR                 "/data/global/music/Act2/lair.wav"
#define MUSIC_ACT2_RADAMENTRESOLUTION   "/data/global/music/Act2/radamentresolution.wav"
#define MUSIC_ACT2_SANCTUARY            "/data/global/music/Act2/sanctuary.wav"
#define MUSIC_ACT2_SEWER                "/data/global/music/Act2/sewer.wav"
#define MUSIC_ACT2_TAINTEDSUNACTION     "/data/global/music/Act2/taintedsunaction.wav"
#define MUSIC_ACT2_TOMBS                "/data/global/music/Act2/tombs.wav"
#define MUSIC_ACT2_TOWN2                "/data/global/music/Act2/town2.wav"
#define MUSIC_ACT2_VALLEY               "/data/global/music/Act2/valley.wav"
#define MUSIC_ACT3_JUNGLE               "/data/global/music/Act3/jungle.wav"
#define MUSIC_ACT3_KURAST               "/data/global/music/Act3/kurast.wav"
#define MUSIC_ACT3_KURASTSEWER          "/data/global/music/Act3/kurastsewer.wav"
#define MUSIC_ACT3_MEFDEATHACTION       "/data/global/music/Act3/mefdeathaction.wav"
#define MUSIC_ACT3_ORBACTION            "/data/global/music/Act3/orbaction.wav"
#define MUSIC_ACT3_SPIDER               "/data/global/music/Act3/spider.wav"
#define MUSIC_ACT3_TOWN3                "/data/global/music/Act3/town3.wav"
#define MUSIC_ACT4_DIABLO               "/data/global/music/Act4/diablo.wav"
#define MUSIC_ACT4_DIABLOACTION         "/data/global/music/Act4/diabloaction.wav"
#define MUSIC_ACT4_FORGEACTION          "/data/global/music/Act4/forgeaction.wav"
#define MUSIC_ACT4_IZUALACTION          "/data/global/music/Act4/izualaction.wav"
#define MUSIC_ACT4_MESA                 "/data/global/music/Act4/mesa.wav"
#define MUSIC_ACT4_TOWN4                "/data/global/music/Act4/town4.wav"
#define MUSIC_ACT5_BAAL                 "/data/global/music/Act5/baal.wav"
#define MUSIC_ACT5_SIEGE                "/data/global/music/Act5/siege.wav"
#define MUSIC_ACT5_SHENK                "/data/global/music/Act5/shenkmusic.wav"
#define MUSIC_ACT5_XTOWN                "/data/global/music/Act5/xtown.wav"
#define MUSIC_ACT5_XTEMPLE              "/data/global/music/Act5/xtemple.wav"
#define MUSIC_ACT5_ICECAVES             "/data/global/music/Act5/icecaves.wav"
#define MUSIC_ACT5_NIHLATHAK            "/data/global/music/Act5/nihlathakmusic.wav"
#endif // ABYSS_RESOURCEPATHS_H
