# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false

            matrix:
                include:
                    -   name: Windows (MSVC)
                        os: windows-latest
                        c_compiler: cl
                        cpp_compiler: cl
                        triplet: x64-windows-release
                    -   name: Ubuntu GCC
                        os: ubuntu-latest
                        c_compiler: gcc
                        cpp_compiler: g++
                        triplet: x64-linux-release
                    -   name: MacOS (Clang)
                        os: macos-13
                        c_compiler: clang
                        cpp_compiler: clang++
                        triplet: arm64-osx-release

        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    submodules: recursive

            -   name: Set reusable strings
                id: strings
                shell: bash
                run: |
                    echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

            -   name: Get CMake
                uses: lukka/get-cmake@latest

            -   name: Run VCPKG
                uses: lukka/run-vcpkg@v11
                with:
                    vcpkgGitCommitId: 'a34c873a9717a888f58dc05268dea15592c2f0ff'
                    vcpkgJsonGlob: "**/vcpkg.json"


            -   name: Configure CMake
                run: >
                    cmake
                    -GNinja
                    -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
                    -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
                    -B ${{ steps.strings.outputs.build-output-dir }}
                    -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
                    -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
                    -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
                    -S ${{ github.workspace }}

            -   name: Build
                run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

        env:
            VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
            VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.triplet }}

